# バージョンを指定
version: "3.3"

# サービス定義
services:
  # サーバ
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 81:80


  # データベース
  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: isaac
      MYSQL_PASSWORD: docker
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    